- src/main/java/com/backmin/domains/menu/domain/MenuOption.java
- src/main/java/com/backmin/domains/store/controller/CategoryController.java
- src/main/java/com/backmin/domains/store/converter/CategoryConverter.java
- src/main/java/com/backmin/domains/store/domain/Category.java
- src/main/java/com/backmin/domains/store/domain/CategoryRepository.java
- src/main/java/com/backmin/domains/store/dto/CategoryDto.java
- src/main/java/com/backmin/domains/store/dto/CategoryInfoAtList.java
- src/main/java/com/backmin/domains/store/dto/ReadAllCategoriesResponse.java
- src/main/java/com/backmin/domains/store/service/CategoryService.java
- src/test/java/com/backmin/domains/store/controller/CategoryControllerTest.java
- src/test/java/com/backmin/domains/store/domain/CategoryRepositoryTest.java
- src/test/java/com/backmin/domains/store/service/CategoryServiceTest.java
> [기능] 카테고리 목록 조회 

- src/main/java/com/backmin/domains/menu/domain/MenuOption.java
- src/main/java/com/backmin/domains/store/controller/CategoryController.java
- src/main/java/com/backmin/domains/store/converter/CategoryConverter.java
- src/main/java/com/backmin/domains/store/domain/Category.java
- src/main/java/com/backmin/domains/store/domain/CategoryRepository.java
- src/main/java/com/backmin/domains/store/dto/CategoryDto.java
- src/main/java/com/backmin/domains/store/dto/CategoryInfoAtList.java
- src/main/java/com/backmin/domains/store/dto/ReadAllCategoriesResponse.java
- src/main/java/com/backmin/domains/store/service/CategoryService.java
- src/test/java/com/backmin/domains/store/controller/CategoryControllerTest.java
- src/test/java/com/backmin/domains/store/domain/CategoryRepositoryTest.java
- src/test/java/com/backmin/domains/store/service/CategoryServiceTest.java
> [기능] 카테고리 목록 조회

- src/main/java/com/backmin/domains/common/enums/ErrorInfo.java
- src/main/java/com/backmin/domains/member/service/MemberService.java
- src/main/java/com/backmin/domains/menu/domain/Menu.java
- src/main/java/com/backmin/domains/menu/domain/MenuOption.java
- src/main/java/com/backmin/domains/order/controller/OrderController.java
- src/main/java/com/backmin/domains/order/domain/Order.java
- src/main/java/com/backmin/domains/order/dto/UpdateOrderStatusRequest.java
- src/main/java/com/backmin/domains/order/service/OrderService.java
- src/main/java/com/backmin/domains/store/domain/Store.java
- src/test/java/com/backmin/domains/order/controller/OrderControllerTest.java
> [기능] 주문 상태 변경 API

- src/main/java/com/backmin/domains/review/domain/Review.java
- src/main/java/com/backmin/domains/review/domain/ReviewRepository.java
- src/main/java/com/backmin/domains/store/converter/StoreConverter.java
- src/main/java/com/backmin/domains/store/dto/StoreInfoAtList.java
- src/main/java/com/backmin/domains/store/service/StoreService.java
- src/test/java/com/backmin/domains/review/domain/ReviewRepositoryTest.java
- src/test/java/com/backmin/domains/store/controller/StoreControllerTest.java
- src/test/java/com/backmin/domains/store/service/StoreServiceTest.java
> [기능] 카테고리 별 가게 목록 조회 - 총 리뷰 개수, 평균 평점 조회 기능 추가

- src/main/java/com/backmin/domains/common/enums/ErrorInfo.java
- src/main/java/com/backmin/domains/store/controller/StoreController.java
- src/main/java/com/backmin/domains/store/domain/StoreRepository.java
- src/main/java/com/backmin/domains/store/service/StoreService.java
- src/test/java/com/backmin/domains/store/controller/StoreControllerTest.java
- src/test/java/com/backmin/domains/store/domain/StoreRepositoryTest.java
- src/test/java/com/backmin/domains/store/service/StoreServiceTest.java
> [기능] 가게명 검색

- src/main/java/com/backmin/domains/order/converter/OrderConverter.java
- src/main/java/com/backmin/domains/store/service/StoreService.java
- src/test/java/com/backmin/domains/member/domain/MemberTest.java
> [Refactor] Conflict 해결

- src/main/java/com/backmin/domains/member/dto/response/MemberOrderPageResult.java
- src/main/java/com/backmin/domains/order/converter/OrderConverter.java
- src/test/java/com/backmin/domains/order/controller/OrderControllerTest.java
> [기능] 오더 API 문서화

- src/test/java/com/backmin/domains/store/controller/CategoryControllerTest.java
- src/test/java/com/backmin/domains/store/controller/StoreControllerTest.java
> [Feat] RestDocs 문서를 작성하라

- src/main/java/com/backmin/domains/menu/domain/Menu.java
- src/main/java/com/backmin/domains/store/domain/Store.java
- src/test/java/com/backmin/domains/member/domain/MemberTest.java
- src/test/java/com/backmin/domains/menu/domain/MenuRepositoryTest.java
- src/test/java/com/backmin/domains/order/controller/OrderControllerTest.java
- src/test/java/com/backmin/domains/review/domain/ReviewRepositoryTest.java
- src/test/java/com/backmin/domains/store/domain/StoreRepositoryTest.java
> [리펙토링] 전체 소스 리펙토링 진행

- src/main/java/com/backmin/domains/store/domain/Store.java
Reverts prgrms-be-devcourse/BEDV1_BackMin#64
> Revert "[리펙토링] Category Entity의 연관관계를 수정하라"

- src/main/java/com/backmin/domains/store/service/StoreService.java
Reverts prgrms-be-devcourse/BEDV1_BackMin#63
> Revert "[리펙토링] 예외 발생 로직을 수정하라"

- src/main/java/com/backmin/domains/menu/domain/Menu.java
- src/main/java/com/backmin/domains/store/domain/Store.java
- src/test/java/com/backmin/domains/member/domain/MemberRepositoryTest.java
- src/test/java/com/backmin/domains/menu/domain/MenuRepositoryTest.java
- src/test/java/com/backmin/domains/order/controller/OrderControllerTest.java
- src/test/java/com/backmin/domains/review/domain/ReviewRepositoryTest.java
- src/test/java/com/backmin/domains/store/domain/CategoryRepositoryTest.java
- src/test/java/com/backmin/domains/store/domain/StoreRepositoryTest.java
- Category Entity의 연관관계 수정
-  Repository Layer 테스트 코드에"DataJpaTest"를 "SpringBootTest"로 변경
-  Store에 desctiption 필드 오타 변경
-  Store에 BaseEntity 상속Store에 BaseEntity 상속받도록 수정받도록 수정
-  OrderControllerTest에 CategoryRepository도 tearDown()에 추가
> [Refactor] 전체 소스 리팩토링을 진행하라

- src/docs/index.adoc
- src/test/java/com/backmin/domains/member/domain/MemberRepositoryTest.java
MemberRepositoryTest 영속성에대한 Test 내용 수정 (@TestInstance 어노테이션 추가 및 @BeforeEach -> @BeforeAll 수정)
index.adoc 파일에 request, response에 대한 내용 기술
> MemberRepositoryTest 영속성에대한 Test 내용 수정, 문서화 추가

- src/main/java/com/backmin/domains/menu/domain/Menu.java
- src/main/java/com/backmin/domains/order/controller/OrderController.java
- src/main/java/com/backmin/domains/order/service/OrderService.java
- src/test/java/com/backmin/domains/order/controller/OrderControllerTest.java
> Fix: order test 버그 수정

- src/main/java/com/backmin/domains/common/enums/ErrorInfo.java
- src/main/java/com/backmin/domains/member/domain/Member.java
- src/main/java/com/backmin/domains/member/service/MemberService.java
- src/test/java/com/backmin/domains/member/controller/MemberControllerTest.java
- src/test/java/com/backmin/domains/review/controller/ReviewControllerTest.java
- src/test/java/com/backmin/domains/review/domain/ReviewRepositoryTest.java
- src/test/java/com/backmin/domains/store/controller/StoreControllerTest.java
- src/test/java/com/backmin/domains/store/domain/StoreRepositoryTest.java
- src/test/java/com/backmin/domains/store/service/StoreServiceTest.java
> 테스트 케이스 추가 및 멤버 생성시 형식 확인 추가

- src/main/java/com/backmin/domains/menu/domain/Menu.java
- src/main/java/com/backmin/domains/store/domain/StoreRepository.java
- src/test/java/com/backmin/domains/store/controller/StoreControllerTest.java
- src/test/java/com/backmin/domains/store/service/StoreServiceTest.java
> [Refactor] Controller, Service 테스트 코드에서 Transactional 어노테이션을 제거하라

- src/main/java/com/backmin/config/util/AssertThrow.java
- src/main/java/com/backmin/domains/common/enums/ErrorInfo.java
- src/main/java/com/backmin/domains/member/service/MemberService.java
- src/main/java/com/backmin/domains/menu/domain/Menu.java
- src/main/java/com/backmin/domains/order/controller/OrderController.java
- src/main/java/com/backmin/domains/order/service/OrderService.java
- src/test/java/com/backmin/domains/order/controller/OrderControllerTest.java
> [리팩토링] 예외 발생 코드 분리, 테스트 케이스 추가

- src/main/java/com/backmin/domains/common/dto/PageResult.java
- src/main/java/com/backmin/domains/store/service/StoreService.java
> [Refactor] PageResult 에 Builder를 제거하라

- src/main/resources/application.yml
> [Feat] 공통 설정파일을 작성하라

- src/main/java/com/backmin/DataSettingRunner.java
- src/main/java/com/backmin/domains/member/service/MemberService.java
- src/main/java/com/backmin/domains/store/domain/Store.java
- 가데이터 로직에 가게 주인 추가
- Store Entity에 Member 필드를 nullable false로 변경
- 닉네임 체크 안되던 소스 수정
> [Refactor] 가데이터 로직에 "가게 주인"도 등록되도록 수정하라

- src/test/java/com/backmin/domains/member/controller/MemberControllerTest.java
- src/test/java/com/backmin/domains/menu/domain/MenuRepositoryTest.java
- src/test/java/com/backmin/domains/review/domain/ReviewRepositoryTest.java
- src/test/java/com/backmin/domains/store/controller/StoreControllerTest.java
- src/test/java/com/backmin/domains/store/domain/StoreRepositoryTest.java
- src/test/java/com/backmin/domains/store/service/StoreServiceTest.java
> [fix] Store Entity 변경으로 인한 테스트코드 실패를 수정하라
